Fixes for grammar
softrams/bulwark pull request #448
Opened 2020-11-21 18:05 UTC by waterweasel4

# Pull Request

Thank you for your contribution to the Bulwark. Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)
N/A

## Type of change

- [ ] A new feature
- [x] A bug fix
- [ ] Documentation only changes
- [x] Changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc)
- [ ] A code change that neither fixes a bug nor adds a feature
- [ ] A code change that improves performance
- [ ] Adding missing tests or correcting existing tests
- [ ] Changes that affect the build system or external dependencies
- [ ] Changes to our CI configuration files and scripts
- [ ] Other changes that don't modify src or test files

Description

```
When an assessment lasts only one day, the report was showing "the assessment last for 1 days" (plural).  This has been changed such that if day = 0, or day > 1, report 'days'.  Otherwise, report 'day'.
```

---

## Checklist

- [x] My code follows the [contributing](../CONTRIBUTING.md) guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

2020-11-21 20:30 UTC, Whamo12 requested changes

2020-11-21 20:30 UTC, Whamo12 commented on package.json
> +    "cz": "^1.8.2",
Is this package needed?

2020-11-21 20:30 UTC, Whamo12 commented on frontend/src/app/report/report.component.ts
> +      if (this.numOfDays > 1 || this.numOfDays  === 0) {
This would be a good opportunity to use the ternary operator.

2020-11-23 12:45 UTC, Whamo12 commented on package.json
> +    "cz": "^1.8.2",
Ah, I get it. You most likely did not have the package installed locally to run the 'npm run commit' script. Go ahead and update the 'npm run commit' script to use npx which allows you to run the script without package installation. 

'npx git-cz'

2020-11-23 14:15 UTC, waterweasel4 reviewed
Added ternary operator and removed my package.json edit.

2020-11-23 14:35 UTC, Whamo12 approved these changes

2020-11-23 14:35 UTC, merged